"""
Live service: the thing that owns a LiveTwin, a set of connectors and the
background loop that moves events from one to the other.

Also generates the synthetic replay session. That session is produced by the
REAL engine (a Simulation with timeline recording and a scripted failure), so
it is a faithful sample of the model's behaviour -- but it is a simulation, not
a measurement, and everything it emits is labelled REPLAY / synthetic.
"""
from __future__ import annotations

import copy
import queue
import threading
import time
from typing import Any, Dict, List, Optional

from dtwin.engine import Simulation
from dtwin.model import INF, Dist, Plant
from dtwin.live.connectors import (CONNECTED, ERROR, Connector,
                                   ReplayConnector)
from dtwin.live.events import (BLOCKED, BUSY, DOWN, SETUP, STARVED,
                               STATE_CHANGE, Event)
from dtwin.live.twin import LiveTwin

TICK = 0.2


# ==========================================================================
# Synthetic session generation (from the real engine)
# ==========================================================================
def generate_synthetic_session(plant: Plant, horizon: float = 5400.0,
                               seed: int = 7,
                               fault_stage: Optional[str] = None
                               ) -> List[dict]:
    """Run the engine with timeline recording and turn the state timeline into
    replayable event records.

    A failure is scripted into one stage (by default the second stage, or the
    slowest one if there are fewer than two) so the session contains a real
    fault and its real blocked/starved propagation, computed by the engine
    rather than written by hand.
    """
    p = copy.deepcopy(plant)
    p.horizon = float(horizon)
    p.warmup = 0.0
    if not p.stages:
        return []
    if fault_stage is None:
        idx = 1 if len(p.stages) > 1 else 0
    else:
        idx = p.index(fault_stage)
    s = p.stages[idx]
    if s.mtbf == INF or s.mtbf > horizon / 3:
        s.mtbf = max(120.0, horizon / 6.0)
    if s.repair.mean <= 0:
        s.repair = Dist("det", max(60.0, s.proc.mean * 8), 0.0)

    sim = Simulation(p, seed=seed, record_timeline=True,
                     timeline_cap=20000).run()

    stage_ids = [st.id for st in p.stages]
    out: List[dict] = []
    prev: Dict[tuple, Optional[str]] = {}
    for (t, si, mi, state) in sim.timeline:
        if si < 0 or si >= len(stage_ids):
            continue
        sid = stage_ids[si]
        nmach = p.stages[si].machines
        mid = f"{sid}-M{mi + 1}" if nmach > 1 else sid
        if state not in (BUSY, SETUP, DOWN, BLOCKED, STARVED):
            continue
        key = (sid, mid)
        out.append({
            "offset": float(t),
            "stage": sid, "machine": mid,
            "event_type": STATE_CHANGE,
            "previous_state": prev.get(key),
            "new_state": state,
        })
        prev[key] = state
    return out


def synthetic_replay_connector(plant: Plant, speed: float = 120.0,
                               cid: str = "replay",
                               horizon: float = 5400.0) -> ReplayConnector:
    events = generate_synthetic_session(plant, horizon=horizon)
    c = ReplayConnector(
        cid, "Synthetic replay generated by the engine", events, speed=speed,
        source_label="synthetic replay generated by the engine")
    c.notes.append("REPLAY: engine-generated session, not measured data.")
    return c


# ==========================================================================
# Live service
# ==========================================================================
class LiveService:
    """Owns one live twin and its connectors, and pumps events between them."""

    def __init__(self, twin: LiveTwin):
        self.twin = twin
        self.connectors: Dict[str, Connector] = {}
        self.order: List[str] = []
        self._thread: Optional[threading.Thread] = None
        self._stop = threading.Event()
        self.started_at: Optional[float] = None
        self.anomalies: List[dict] = []
        self.detector = None            # set by the anomaly layer
        self.last_tick: Optional[float] = None

    # ---- connectors -------------------------------------------------------
    def add(self, c: Connector, connect: bool = True) -> Connector:
        self.connectors[c.id] = c
        if c.id not in self.order:
            self.order.append(c.id)
        if connect:
            c.connect()
        return c

    def remove(self, cid: str) -> None:
        c = self.connectors.pop(cid, None)
        if c:
            c.disconnect()
        if cid in self.order:
            self.order.remove(cid)

    def statuses(self) -> List[dict]:
        return [self.connectors[cid].status() for cid in self.order
                if cid in self.connectors]

    def primary(self) -> Optional[Connector]:
        for cid in self.order:
            c = self.connectors.get(cid)
            if c and c.state == CONNECTED:
                return c
        return self.connectors.get(self.order[0]) if self.order else None

    # ---- pump -------------------------------------------------------------
    def tick(self, now: Optional[float] = None) -> int:
        now = time.time() if now is None else now
        self.last_tick = now
        applied = 0
        for cid in list(self.order):
            c = self.connectors.get(cid)
            if c is None:
                continue
            for ev in c.poll(now):
                ok, _ = self.twin.apply(ev)
                applied += 1 if ok else 0
                if ok and self.detector is not None:
                    for a in self.detector.observe(ev, self.twin):
                        self.anomalies.append(a)
                        if len(self.anomalies) > 200:
                            self.anomalies.pop(0)
        return applied

    def start(self) -> None:
        if self._thread and self._thread.is_alive():
            return
        self._stop.clear()
        self.started_at = time.time()

        def loop():
            while not self._stop.is_set():
                try:
                    self.tick()
                except Exception:
                    pass
                self._stop.wait(TICK)

        self._thread = threading.Thread(target=loop, daemon=True,
                                        name="live-service")
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()
        for c in self.connectors.values():
            c.disconnect()

    # ---- views ------------------------------------------------------------
    def connection_badge(self) -> dict:
        """What the UI badge must say. Honest by construction: the delivery
        field comes from the connector class, not from a label we choose."""
        c = self.primary()
        if c is None:
            return {"state": "disconnected", "source": None, "label": "none",
                    "delivery": None, "replay": False, "last_update": None}
        st = c.status()
        return {
            "state": st["state"], "source": st["source_label"],
            "label": st["label"], "delivery": st["delivery"],
            "replay": st["delivery"] == "replay",
            "live": st["delivery"] == "live" and st["state"] == CONNECTED,
            "last_update": st["last_update"], "error": st["error"],
            "notes": st["notes"],
        }

    def snapshot(self, events: int = 60) -> dict:
        snap = self.twin.snapshot(events=events)
        snap["connection"] = self.connection_badge()
        snap["connectors"] = self.statuses()
        snap["anomalies"] = self.anomalies[-40:]
        return snap

    # ---- SSE --------------------------------------------------------------
    def subscribe(self) -> "queue.Queue":
        q: queue.Queue = queue.Queue(maxsize=500)
        self.twin.subscribe(q)
        return q

    def unsubscribe(self, q) -> None:
        self.twin.unsubscribe(q)
