"""
HTTP surface for the live intake layer.

Like server/api.py this file contains no analytics: it wires requests to
dtwin.live and dtwin.ingest and makes the results JSON-safe. Every label it
emits ("REPLAY", "unconfigured") is derived from the connector's own state, not
chosen here.
"""
from __future__ import annotations

import os
import queue
import threading
import time
from typing import Dict, Optional

from dtwin.live.connectors import (CONNECTED, FileConnector, MDFSConnector,
                                   RESTConnector, SQLConnector)
from dtwin.live.service import LiveService, synthetic_replay_connector
from dtwin.live.twin import LiveTwin

LIVE: Dict[str, LiveService] = {}
LIVE_LOCK = threading.Lock()

REPLAY_LABEL = "synthetic replay generated by the engine"


def get(session_id: str) -> Optional[LiveService]:
    return LIVE.get(session_id)


def start(sess, source: str = "replay", speed: float = 120.0,
          horizon: float = 5400.0, **kw) -> LiveService:
    """Create (or replace) the live service for a session.

    The live twin gets its own deep copy of the Plant: the simulation twin and
    the live twin are separate objects and neither can mutate the other.
    """
    stop(sess.id)
    twin = LiveTwin(sess.plant_for_live() if hasattr(sess, "plant_for_live")
                    else _copy_plant(sess.plant), name=sess.plant.name)
    svc = LiveService(twin)

    if source == "mdfs":
        mdfs = MDFSConnector("mdfs", profile=MDFSConnector.default_profile())
        if mdfs.connect():
            svc.add(mdfs, connect=False)
        else:
            # A failed live source is never presented as a live feed; the
            # connected primary becomes an explicitly labelled replay.
            svc.add(synthetic_replay_connector(twin.plant, speed=speed,
                                               horizon=horizon))
    elif source == "rest":
        svc.add(RESTConnector("rest", kw.get("label", "REST source"),
                              kw["url"], field_map=kw.get("field_map"),
                              interval=float(kw.get("interval", 5.0)),
                              records_key=kw.get("records_key")))
    elif source == "sql":
        svc.add(SQLConnector("sql", kw.get("label", "SQL source"), kw["path"],
                             kw["query"], field_map=kw.get("field_map"),
                             interval=float(kw.get("interval", 5.0))))
    elif source == "file":
        svc.add(FileConnector("file", kw.get("label", "Event file"),
                              kw["path"], speed=speed))
    else:
        svc.add(synthetic_replay_connector(twin.plant, speed=speed,
                                           horizon=horizon))

    try:
        from dtwin.live.anomaly import AnomalyDetector
        svc.detector = AnomalyDetector(twin.plant)
    except Exception:
        svc.detector = None

    svc.start()
    with LIVE_LOCK:
        LIVE[sess.id] = svc
        if len(LIVE) > 20:
            oldest = sorted(LIVE.items(),
                            key=lambda kv: kv[1].started_at or 0)[0][0]
            old = LIVE.pop(oldest, None)
            if old:
                old.stop()
    return svc


def stop(session_id: str) -> None:
    with LIVE_LOCK:
        svc = LIVE.pop(session_id, None)
    if svc:
        svc.stop()


def _copy_plant(plant):
    import copy
    return copy.deepcopy(plant)


def stream(handler, svc: LiveService) -> None:
    """Server-sent events. One event per line of the live ledger.

    Runs on its own request thread (the server is a ThreadingHTTPServer), so a
    subscriber cannot stall ingestion; a slow client's queue simply overflows
    and drops frames.
    """
    handler.send_response(200)
    handler.send_header("Content-Type", "text/event-stream")
    handler.send_header("Cache-Control", "no-store")
    handler.send_header("Connection", "close")
    handler.send_header("Access-Control-Allow-Origin", "*")
    handler.end_headers()
    q = svc.subscribe()
    deadline = time.time() + 1800
    try:
        handler.wfile.write(b"retry: 2000\n\n")
        handler.wfile.flush()
        last_beat = time.time()
        while time.time() < deadline:
            try:
                ev = q.get(timeout=1.0)
            except queue.Empty:
                ev = None
            import json as _json
            if ev is not None:
                handler.wfile.write(
                    b"event: tick\ndata: " +
                    _json.dumps(ev).encode() + b"\n\n")
                handler.wfile.flush()
            if time.time() - last_beat > 5.0:
                last_beat = time.time()
                badge = svc.connection_badge()
                handler.wfile.write(
                    b"event: status\ndata: " +
                    _json.dumps(badge).encode() + b"\n\n")
                handler.wfile.flush()
    except (BrokenPipeError, ConnectionResetError, OSError):
        pass
    finally:
        svc.unsubscribe(q)
